appoint/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('account.urls')),
    path('home/', include('home.urls')),
    path('appoint/', include('meeting.urls')),
    path('etoila/', admin.site.urls),
]

admin.site.site_header = "Appoint"
admin.site.site_title = "Appoint"
admin.site.index_title = "Appoint Administration"

home/urls.py
from django.urls import path
from home.views import IndexView, get_data, UsersView, Todo_Delete, TodoUpdate


urlpatterns = [
    path('', IndexView, name='home'),
    path('delete/<int:pk>', Todo_Delete.as_view(), name='del'),
    path('edit/<int:pk>', TodoUpdate.as_view(), name='todo_update'),
    path('users/', UsersView.as_view(), name='users'),
    path('api/', get_data, name='api'),
]

meeting/urls.py
from django.urls import path
from meeting.views import AppointList, AppointCreate, AppointUpdate, AppointDetail, AppointSearch, AddressCreate, AddressList, AddressUpdate, validate_address, validate_name

urlpatterns = [
    path('search/', AppointSearch.as_view(), name='search_meeting'),
    path('', AppointList.as_view(), name='meeting-list'),
    path('create/', AppointCreate.as_view(), name='meeting-create'),
    path('validate/', validate_name, name='meeting-validate'),
    path('create/address/', AddressCreate.as_view(), name='address-create'),
    path('address/', AddressList.as_view(), name='address-list'),
    path('address/validate', validate_address, name='address-validate'),
    path('address/<int:pk>', AddressUpdate.as_view(), name='address-update'),
    path('<slug:slug>/edit/', AppointUpdate.as_view(), name='meeting-update'),
    path('<slug:slug>/', AppointDetail.as_view(), name='meeting-detail'),


]

meeting/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from meeting.utils import get_unique_slug
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse


# Create your models here.

class Place_Of_Residence(models.Model):
    address = models.CharField(max_length=255, unique=True)
    REGION = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
    )
    region = models.CharField(max_length=12, choices=REGION, default='1')

    def __str__(self):
        return self.address


class Appointment(models.Model):
    CHILDREN_NUMBER_CHOICES = (
        ('Na', 'Na'),
        ('0', '0'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
        ('13', '13'),
        ('14', '14'),

    )
    REASON_CHOICES = (
        ('', ''),
        ('Social Aid', 'Social Aid'),
        ('BIP', 'BIP'),
        ('Industrial Relations,', 'Industrial Relations,'),
        ('employment', 'employment'),
        ('Housing', ' Housing'),
        ('NEF', 'NEF'),
        ('Consumer protection', 'Consumer protection'),
        ('other', 'other'),
    )
    MARITAL_STATUS = (
        ('single', 'single'),
        ('married', 'married'),
        ('widowed', 'widowed'),
        ('divorced', 'divorced'),
        ('cohabitation', 'cohabitation'),
    )
    STATUS_CHOICES = (
        ('completed', 'completed'),
        ('pending', 'pending'),
        ('important', 'important'),
        ('follow up', 'follow up'),
    )
    staff = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=255, blank=True, unique=True)
    first_Name = models.CharField(max_length=255)
    last_Name = models.CharField(max_length=255)
    NIC = models.CharField(max_length=255, default='xxxx')
    telephone = PhoneNumberField(blank=True)
    address = models.ForeignKey(Place_Of_Residence, on_delete=models.CASCADE)
    children = models.CharField(max_length=12, choices=CHILDREN_NUMBER_CHOICES, default='Na')
    marital_Status = models.CharField(max_length=20, choices=MARITAL_STATUS, default='single')
    reasons = models.CharField(max_length=255, choices=REASON_CHOICES, default='')
    remarks = models.TextField(blank=True, )
    status = models.CharField(max_length=14, choices=STATUS_CHOICES, default='pending')
    published = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_Name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'NIC', 'slug')
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('meeting-list', args=[str(self.slug)])

meeting/forms.py
from bootstrap_modal_forms.forms import BSModalForm
from meeting.models import Appointment, Place_Of_Residence
from django import forms


class AppointmentForm(BSModalForm):
    class Meta:
        model = Appointment
        exclude = ['staff', 'slug', 'created_at', 'updated_at']


class AddressForm(BSModalForm):
    class Meta:
        model = Place_Of_Residence
        fields = '__all__'

meeting/views.py
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalReadView, BSModalDeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.http import JsonResponse
from meeting.forms import AppointmentForm, AddressForm
from meeting.models import Appointment, Place_Of_Residence


# Create your views here.
class AddressCreate(LoginRequiredMixin, BSModalCreateView):
    login_url = 'login'
    form_class = AddressForm
    template_name = 'meeting/address.html'
    success_message = 'Address successfully Created'
    success_url = reverse_lazy('meeting-list')


def validate_address(request):
    address = request.GET.get('address', None)
    data = {
        'is_taken': Place_Of_Residence.objects.filter(address__iexact=address).exists()
    }
    return JsonResponse(data)


class AddressUpdate(LoginRequiredMixin, BSModalUpdateView):
    login_url = 'login'
    form_class = AddressForm
    template_name = 'meeting/address_update.html'
    queryset = Place_Of_Residence.objects.all()
    success_message = 'Address successfully Added'
    success_url = reverse_lazy('address-list')


class AddressList(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Place_Of_Residence
    queryset = Place_Of_Residence.objects.all().order_by('address')
    template_name = 'meeting/address_list.html'
    context_object_name = 'addresses'


class AppointCreate(LoginRequiredMixin, BSModalCreateView):
    login_url = 'login'
    form_class = AppointmentForm
    template_name = 'meeting/create.html'
    success_message = 'Appointment has been created successfully'
    success_url = reverse_lazy('meeting-list')

    def form_valid(self, form):
        form.instance.staff = self.request.user
        return super().form_valid(form)


def validate_name(request):
    first = request.GET.get('first_Name', None)
    last = request.GET.get('last_Name', None)
    tel = request.GET.get('telephone', None)
    data = {
        'exists': Appointment.objects.filter(first_Name__iexact=first).exists(),
        'exists2': Appointment.objects.filter(last_Name__iexact=last).exists(),
        'exists3': Appointment.objects.filter(telephone__exact=tel).exists(),
    }
    return JsonResponse(data)


class AppointUpdate(LoginRequiredMixin, BSModalUpdateView):
    login_url = 'login'
    form_class = AppointmentForm
    queryset = Appointment.objects.all()
    template_name = 'meeting/edit.html'
    success_message = 'Appointment Updated Successfully'
    success_url = reverse_lazy('meeting-list')

    def form_valid(self, form):
        form.instance.staff = self.request.user
        return super().form_valid(form)


class AppointList(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Appointment
    queryset = Appointment.objects.order_by('-published')
    context_object_name = 'meetings'
    template_name = 'meeting/index.html'
    paginate_by = 10


class AppointDetail(BSModalReadView, LoginRequiredMixin):
    login_url = 'login'
    model = Appointment
    template_name = 'meeting/detail.html'
    queryset = Appointment.objects.all()
    context_object_name = 'appoint'


class AppointSearch(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Appointment
    template_name = 'meeting/search.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Appointment.objects.filter(
            Q(first_Name__icontains=query) | Q(last_Name__icontains=query) | Q(NIC__istartswith=query) | Q(
                address__region__contains=query) \
            | Q(status__contains=query) | Q(address__address__istartswith=query) | Q(telephone__exact=query) \
            | Q(reasons__icontains=query)
        )
        return object_list

templates/meeting/address.html
{% load crispy_forms_tags %}
<form method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title text-uppercase text-center text-primary">New Address</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true"><span class="fa fa-close"></span></span>
    </button>
  </div>

  <div class="modal-body">
  {{form|crispy}}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-block btn-outline-success">Create</button>
  </div>
    <style>
        .btn{
            border-radius: 30px;
        }
        .fa-close:hover{
            color: red;
        }
    </style>
</form>
<script>
$('#id_address').keyup(function(){
    let address = $(this).val();

    $.ajax({
        url: '/appoint/address/validate',
        data: {
            address: address

        },
        dataType: 'json',
        success: function (data) {
            if(data.is_taken)
                $('#id_address').css('border-bottom', 'solid 4px red');
            else
                $('#id_address').css('border-bottom', 'solid 4px green');

        }


    })
})
</script>

templates/meeting/address_list.html
{% extends 'base.html' %}
{% block title %}
Address List
{% endblock %}
{% block main %}
{% if request.user.is_authenticated %}
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Address</th>
      <th scope="col">Region</th>
      <th scope="col">Update</th>
    </tr>
  </thead>
  <tbody>
  {% for foo in addresses %}

    <tr>
      <td>{{ foo.address|upper }}</td>
      <td>{{ foo.region }}</td>
      <td><button class="address_update btn btn-outline-light" data-id="{% url 'address-update' foo.id %}">Update</button></td>

  {% endfor %}
   </tr>
  </tbody>
</table>
{% endif %}
    <script>
         $(document).ready(function() {

             $(".address_update").each(function () {
                 $(this).modalForm({formURL: $(this).data('id')});
             });
         })
    </script>
{% endblock %}

templates/meeting/address_update.html
{% load crispy_forms_tags %}
<form method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Address</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
  {{form|crispy}}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-block btn-outline-success">Update</button>
  </div>

</form>

templates/meeting/create.html
<form method="post" action="" enctype="multipart/form-data">

  <div class="modal-header">
    <h3 class="modal-title text-uppercase text-center text-primary">Create New Appointment</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true"><span class="fa fa-close"></span></span>
    </button>
  </div>

  <div class="modal-body">
  {% include 'forms.html' %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-block btn-outline-success">Create</button>
  </div>
    <style>
        .btn{
            border-radius: 30px;
        }
        .fa-close:hover{
            color: red;
        }
    </style>
</form>

<script>
    $.date = function() {
        let date = new Date();
        let day = date.getDate();
        let month = date.getMonth()+1;
        let year = date.getFullYear();
        let d =  month + "/" + day + "/" + year;
        return d;
    };
    $('#id_published').datepicker({
        showOtherMonths:true,
        modal: true,
        header: true,
        footer: true,
        value: $.date,

    });
    $('#id_first_Name').keyup(function(){
        let first_Name = $(this).val();
        $.ajax({
            url: '{% url 'meeting-validate' %}',
            data: {
                first_Name: first_Name,
            },
            dataType: 'json',
            success: function (data) {
                if(data.exists)
                    $('#id_first_Name').css('border-bottom', 'solid 4px red');
                else
                    $('#id_first_Name').css('border-bottom', 'solid 4px green');
            }
        })
    });
    $('#id_last_Name').change(function(){
        let last_Name = $(this).val();

        $.ajax({
            url: '{% url 'meeting-validate' %}',
            data: {
                last_Name: last_Name,
            },
            dataType: 'json',
            success: function (data) {
                if(data.exists2)
                    $('#id_last_Name').css('border-bottom', 'solid 4px red');
                else
                    $('#id_last_Name').css('border-bottom', 'solid 4px green');
            }
        })
    });
    $('#id_telephone').change(function(){
        let telephone= $(this).val();
        $.ajax({
            url: '{% url 'meeting-validate' %}',
            data: {
                telephone: telephone
            },
            dataType: 'json',
            success: function (data) {
                if(data.exists3)
                    $('#id_telephone').css('border-bottom', 'solid 4px red');
                else
                    $('#id_telephone').css('border-bottom', 'solid 4px green');
            }
        })
    });
</script>

templates/meeting/detail.html
<div class="modal-header">
  <h3 class="modal-title">{{ appoint.first_Name }}  {{ appoint.last_Name }} Details </h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
<h1 class="text-center text-uppercase text-primary">NIC: {{ appoint.NIC }}</h1>
<p>
<span class="text-primary text-uppercase">Address:</span> {{ appoint.address|upper }} <br>
<span class="text-primary text-uppercase">Region:</span> {{ appoint.address.region|upper }}<br>
<span class="text-primary text-uppercase">Telephone:</span> {{ appoint.telephone|upper }}<br>
<span class="text-primary text-uppercase">Number of Children:</span> {{ appoint.children }}<br>
<span class="text-primary text-uppercase">Marital Status:</span> {{ appoint.marital_Status|upper }}<br>
<span class="text-primary text-uppercase">Reasons:</span> {{ appoint.reasons|linebreaksbr }}<br>
    {% if request.user.is_superuser %}
        <span class="text-primary text-uppercase">Remarks:</span> {{ appoint.remarks|linebreaksbr }}<br>
    {% endif %}

</p>
<div style="text-align: right;" class=" text-muted">
{{appoint.published|date}} <br>
updated by: {{appoint.staff}}
</div>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-block btn-outline-info" data-dismiss="modal">Close</button>
</div>

templates/meeting/edit.html
{% load crispy_forms_tags %}
<form method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Appointment</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
  {{form|crispy}}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-block btn-outline-success">Update</button>
  </div>

</form>

templates/meeting/index.html
{% extends 'base.html' %}
{% block title %}
Appointments
{% endblock %}
{% block main %}

{% if request.user.is_authenticated %}
{% if request.user.is_active %}
    {% if request.user.is_superuser %}
         <input type="button"  value="Export To Excel" style="float: right;" class="btn btn-outline-primary" onclick="Export()" />
    {% endif %}
    <br>
    <br>
    <table class="table table-dark table-bordered" id="appointTable">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">NIC</th>
      <th scope="col">Telephone</th>
      <th scope="col">Address</th>
      <th scope="col">Region</th>
      <th scope="col">Reasons</th>
      <th scope="col">Status</th>
      <th scope="col">Meeting Date</th>
      <th scope="col">View</th>
      <th scope="col">Update</th>

    </tr>
  </thead>
  <tbody>
  {% for meeting in meetings %}
      {% if meeting.status == "pending" %}
          <tr class="bg-info">
          <td>{{ meeting.first_Name|upper }}</td>
          <td>{{ meeting.last_Name|upper}}</td>
          <td>{{ meeting.NIC|upper }}</td>
          <td>{{ meeting.telephone|upper }}</td>
          <td>{{ meeting.address|upper }}</td>
          <td>{{ meeting.address.region|upper }}</td>
          <td>{{ meeting.reasons|upper }}</td>
          <td>{{ meeting.status|upper }}</td>
          <td>{{ meeting.published|date}}</td>
          {% if request.user.is_superuser %}
              <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
              <td><button class=" meeting_update btn btn-outline-danger" data-id="{% url 'meeting-update' meeting.slug %}">Update</button></td>
          {% else %}
              <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
              <td><button class=" meeting_update btn btn-outline-danger disabled">Update</button></td>
          {% endif %}

        {% endif %}
  </tr>
      {% if meeting.status == "completed" %}
          <tr class="bg-success">
          <td>{{ meeting.first_Name|upper }}</td>
          <td>{{ meeting.last_Name|upper}}</td>
          <td>{{ meeting.NIC|upper }}</td>
          <td>{{ meeting.telephone|upper }}</td>
          <td>{{ meeting.address|upper }}</td>
          <td>{{ meeting.address.region|upper }}</td>
          <td>{{ meeting.reasons|upper }}</td>
          <td>{{ meeting.status|upper }}</td>
          <td>{{ meeting.created_at|date}}</td>
          {% if request.user.is_superuser %}
              <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
              <td><button class=" meeting_update btn btn-outline-danger" data-id="{% url 'meeting-update' meeting.slug %}">Update</button></td>
          {% else %}
              <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
              <td><button class=" meeting_update btn btn-outline-danger disabled">Update</button></td>
          {% endif %}
      {% endif %}
  </tr>
      {% if meeting.status == "important" %}
          <tr class="bg-warning">
          <td>{{ meeting.first_Name|upper }}</td>
          <td>{{ meeting.last_Name|upper}}</td>
          <td>{{ meeting.NIC|upper }}</td>
          <td>{{ meeting.telephone|upper }}</td>
          <td>{{ meeting.address|upper }}</td>
          <td>{{ meeting.address.region|upper }}</td>
          <td>{{ meeting.reasons|upper }}</td>
          <td>{{ meeting.status|upper }}</td>
          <td>{{ meeting.created_at|date}}</td>
          {% if request.user.is_superuser %}
              <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
              <td><button class=" meeting_update btn btn-outline-danger" data-id="{% url 'meeting-update' meeting.slug %}">Update</button></td>
          {% else %}
              <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
              <td><button class=" meeting_update btn btn-outline-danger disabled">Update</button></td>
          {% endif %}
      {% endif %}
  </tr>
{% if meeting.status == "follow up" %}
          <tr class="bg-secondary">
          <td>{{ meeting.first_Name|upper }}</td>
          <td>{{ meeting.last_Name|upper}}</td>
          <td>{{ meeting.NIC|upper }}</td>
          <td>{{ meeting.telephone|upper }}</td>
          <td>{{ meeting.address|upper }}</td>
          <td>{{ meeting.address.region|upper }}</td>
          <td>{{ meeting.reasons|upper }}</td>
          <td>{{ meeting.status|upper }}</td>
          <td>{{ meeting.created_at|date}}</td>
              {% if request.user.is_superuser %}
                  <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
                  <td><button class=" meeting_update btn btn-outline-danger" data-id="{% url 'meeting-update' meeting.slug %}">Update</button></td>
              {% else %}
                  <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
                  <td><button class=" meeting_update btn btn-outline-danger disabled">Update</button></td>
              {% endif %}
{% endif %}
  </tr>
  {% endfor %}
  </tbody>
</table>
{% include 'pagination.html' %}
{% endif %}
{% endif %}

    <script>
    $(document).ready(function(){

        $(".meeting_update").each(function () {
            $(this).modalForm({formURL: $(this).data('id')});
        });

        $(".meeting_detail").each(function () {
            $(this).modalForm({formURL: $(this).data('id')});
        });

    });
    function Export() {
            $("#appointTable").table2excel({
                name: "Appointment",
                filename: "AppointList.xls"
            });
        }
</script>

{% endblock %}

templates/meeting/search.html
{% extends 'base.html' %}
{% block title %}
Search Results
{% endblock %}

{% block main %}
    {% with object_list.count as results_count %}
    <h2 class="text-center text-uppercase">Result{{ results_count| pluralize }} Found {{ results_count }} </h2>
    {% endwith %}
 <input type="button"  value="Export To Excel" style="float: right;" class="btn btn-outline-secondary" onclick="Export()" />
    <br>
    <br>
    <table class="table table-dark table-bordered" id="searchTable">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">NIC</th>
      <th scope="col">Telephone</th>
      <th scope="col">Address</th>
      <th scope="col">Region</th>
      <th scope="col">Reasons</th>
      <th scope="col">Status</th>
      <th scope="col">Date of Meeting</th>
      <th scope="col">View</th>
      <th scope="col">Update</th>


    </tr>
  </thead>
  <tbody>
  {% for meeting in object_list %}
      {% if meeting.status == "pending" %}
          <tr class="bg-info">
          <td>{{ meeting.first_Name|upper }}</td>
          <td>{{ meeting.last_Name|upper}}</td>
          <td>{{ meeting.NIC|upper }}</td>
          <td>{{ meeting.telephone|upper }}</td>
          <td>{{ meeting.address|upper }}</td>
          <td>{{ meeting.address.region|upper }}</td>
          <td>{{ meeting.reasons|upper }}</td>
          <td>{{ meeting.status|upper }}</td>
          <td>{{ meeting.published}}</td>
          <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
          <td><button class=" meeting_update btn btn-outline-danger" data-id="{% url 'meeting-update' meeting.slug %}">Update</button></td>
        {% endif %}
  </tr>
      {% if meeting.status == "completed" %}
          <tr class="bg-success">
          <td>{{ meeting.first_Name|upper }}</td>
          <td>{{ meeting.last_Name|upper}}</td>
          <td>{{ meeting.NIC|upper }}</td>
          <td>{{ meeting.telephone|upper }}</td>
          <td>{{ meeting.address|upper }}</td>
          <td>{{ meeting.address.region|upper }}</td>
          <td>{{ meeting.reasons|upper }}</td>
          <td>{{ meeting.status|upper }}</td>
          <td>{{ meeting.published}}</td>
          <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
          <td><button class=" meeting_update btn btn-outline-danger" data-id="{% url 'meeting-update' meeting.slug %}">Update</button></td>
      {% endif %}
  </tr>
      {% if meeting.status == "important" %}
          <tr class="bg-warning">
          <td>{{ meeting.first_Name|upper }}</td>
          <td>{{ meeting.last_Name|upper}}</td>
          <td>{{ meeting.NIC|upper }}</td>
          <td>{{ meeting.telephone|upper }}</td>
          <td>{{ meeting.address|upper }}</td>
          <td>{{ meeting.address.region|upper }}</td>
          <td>{{ meeting.reasons|upper }}</td>
          <td>{{ meeting.status|upper }}</td>
          <td>{{ meeting.published}}</td>
          <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
          <td><button class=" meeting_update btn btn-outline-danger" data-id="{% url 'meeting-update' meeting.slug %}">Update</button></td>
      {% endif %}
  </tr>
{% if meeting.status == "follow up" %}
          <tr class="bg-secondary">
          <td>{{ meeting.first_Name|upper }}</td>
          <td>{{ meeting.last_Name|upper}}</td>
          <td>{{ meeting.NIC|upper }}</td>
          <td>{{ meeting.telephone|upper }}</td>
          <td>{{ meeting.address|upper }}</td>
          <td>{{ meeting.address.region|upper }}</td>
          <td>{{ meeting.reasons|upper }}</td>
          <td>{{ meeting.status|upper }}</td>
          <td>{{ meeting.published}}</td>
          <td><button class="meeting_detail btn btn-outline-light" data-id="{% url 'meeting-detail' meeting.slug %}">View</button></td>
          <td><button class=" meeting_update btn btn-outline-danger" data-id="{% url 'meeting-update' meeting.slug %}">Update</button></td>
{% endif %}
  </tr>
  {% endfor %}
  </tbody>
</table>


        <script>
    $(document).ready(function(){
        $(".create_appoint").modalForm({formURL: "{% url 'meeting-create' %}"});

        $(".meeting_update").each(function () {
            $(this).modalForm({formURL: $(this).data('id')});
        });

        $(".meeting_detail").each(function () {
            $(this).modalForm({formURL: $(this).data('id')});
        });

    });
     function Export() {
            $("#searchTable").table2excel({
                name: "Search",
                filename: "Table.xls"
            });
        }

</script>
{% endblock %}